### ISSUE TITLE
Does this moqui ofbiz port integrate the full ofbiz applications?

### ISSUE THREAD

**Issue by topstarnetwork** [jonesde/moqui_ofbiz_10_04#1]
Does this moqui ofbiz port integrate the full ofbiz applications?
In other words will I have a full apache ofbiz blown software ported into moqui platform?

**Comment by jonesde** [comment]
You can see the details in the files in this repository, it is only a set of Moqui entity definitions based on the OFBiz entities from version 10.04 and is over 5 years old... was never used and is not being maintained.
